# Generated by Django 3.2.3 on 2022-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppit', '0003_rename_phon_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=500)),
                ('resume', models.ImageField(upload_to='')),
            ],
        ),
    ]
