# Generated by Django 3.2.3 on 2022-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppit', '0006_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
